Retry PR
coder3000/csc420project pull request #2
Opened 2016-11-25 11:46 UTC by mymjack

Oh those reverts? Yeah I screwed up pretty well. Had some conflicts but now resolved

2016-11-25 22:52 UTC, coder3000 requested changes
Still has some problems

2016-11-25 22:52 UTC, coder3000 commented on findball.m
> +function [xyif, preview] = findBall(dclip)
Can you change the filename to findBall?

2016-11-25 22:52 UTC, coder3000 commented on fitcurve.m
> +function curve = fitcurve(segments)
Not sure why we still have this.. Thought we gonna have one unified function?

2016-11-25 22:52 UTC, coder3000 commented on nneighbours.m
> +            if size(ingroup, 1) <=2
Isn't px always linear and py quadratic?

2016-11-25 22:52 UTC, coder3000 commented on nneighbours.m
> +            psx = polyfit(ingroup(:,4),ingroup(:,1),1);
Why calculate this again?

2016-11-25 22:52 UTC, coder3000 commented on nneighbours.m
> +            [idx, d] = nearest(cp, c(targets,1:2));
You need find multiple second points that are within fixed distance

2016-11-25 22:52 UTC, coder3000 commented on nneighbours.m
> +        if cp(5) ~= 0  % Inner node of some curve is unlikely another start
Clever, but what if a point in second frame is closest to two points in first frame simultaneously?

2016-11-25 22:52 UTC, coder3000 commented on processClip.m
> +[candidates, ~] = findBall(dclip);
We may need to retain cclip for presentation

2016-11-25 22:52 UTC, coder3000 commented on nneighbours.m
> +function cout = nneighbours(candidates)
Where are coefficients of px and py saved?

2016-11-26 00:00 UTC, closed without merging

2016-11-26 00:06 UTC, mymjack commented on nneighbours.m
> +            if size(ingroup, 1) <=2
It was, still can be

2016-11-26 00:06 UTC, mymjack commented on nneighbours.m
> +            psx = polyfit(ingroup(:,4),ingroup(:,1),1);
Straightness penalize purpose

2016-11-26 00:08 UTC, mymjack commented on nneighbours.m
> +        if cp(5) ~= 0  % Inner node of some curve is unlikely another start
Then the first two points in first frame should both find this point in second frame. The challenge is the reverse.